ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: edge
    version: latest
  - name: safari
    version: latest
  - name: iphone
    version: latest
